.include <bsd.own.mk>

SUBDIR+=	hello
SUBDIR+=	berend1
SUBDIR+=	berend2
SUBDIR+=	berend3
SUBDIR+=	berend4
SUBDIR+=	berend5
SUBDIR+=	peter1
SUBDIR+=	peter2
SUBDIR+=	peter3
SUBDIR+=	peter4
SUBDIR+=	peter5
SUBDIR+=	placeholder1
SUBDIR+=	secondtest
SUBDIR+=	mydriver

.include <bsd.subdir.mk>
